### ISSUE TITLE
XFEL： 未找到设备

### ISSUE THREAD

**Issue by unknown10777** [YuzukiHD/Buildroot-YuzukiSBC#2]

**Comment by YuzukiTsuru** [comment]
在文档添加了xfel驱动安装说明

https://yuzukihd.gloomyghost.com/Buildroot-YuzukiSBC/#/?id=xfel-driver-install

**Comment by unknown10777** [comment]
回来报个平安，前两个f1c200s是**深圳市亨源电子科技**购买的，串口屁输出没有
后面从**佳芯微科技电子**购买的f1c100s f1c200s两片，串口终于正常输出了
