### ISSUE TITLE
请求添加默认启动串口输出

### ISSUE THREAD

**Issue by unknown10777** [YuzukiHD/Buildroot-YuzukiSBC#5]
请求添加默认启动串口输出

**Comment by YuzukiTsuru** [comment]
添加到哪里？描述文档吗

**Comment by unknown10777** [comment]
我的意思是console同时输出到串口和显示器

**Comment by unknown10777** [comment]
我刷的是YuzukiRuler v0.0.1版本的，它貌似没有输出

**Comment by YuzukiTsuru** [comment]
串口和SPI屏幕同时有输出的，如果没有可能是因为焊接问题

**Comment by unknown10777** [comment]
请问是哪个版本的release？

**Comment by YuzukiTsuru** [comment]
YuzukiRuler.0.0.1

**Comment by unknown10777** [comment]
请问速率是多少？

**Comment by YuzukiTsuru** [comment]
115200

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/168094011-21797148-f451-4ed5-ad74-9c284458e02e.png)
我刷了您说的固件，但是还是没有任何输出，设备管理器也设置了115200速率

**Comment by YuzukiTsuru** [comment]
可能是没有启动系统，检查下固件烧录

**Comment by unknown10777** [comment]
我运行的指令是xfel spinor write 0 固件，我觉得没有问题，但设备管理器显示的设备是“Unknown Device #1”，并且即使没有按下fel键也可使用xfel工具进行操作，fel键测量通断正常

**Comment by unknown10777** [comment]
还有一点很奇怪的是设备连接到普通usb口不能正常使用xfel，连接到typec口就能正常使用xfel

**Comment by YuzukiTsuru** [comment]
看着没问题

**Comment by YuzukiTsuru** [comment]
屏幕有显示吗

**Comment by unknown10777** [comment]
没有

**Comment by unknown10777** [comment]
我确信自己焊接没问题，我已经拆下来再植锡2次了
