### ISSUE TITLE
无法进入系统

### ISSUE THREAD

**Issue by Leader-txt** [YuzukiHD/Buildroot-YuzukiSBC#6]
启动后卡在
vcc3v0:disabling
vcc3v3:disabling
vcc5v0:disabling

**Comment by YuzukiTsuru** [comment]
请提供板子型号，芯片型号，启动设备等参数

**Comment by Leader-txt** [comment]
板子型号是ruler，芯片是f1c200s，启动设备就是板子直接上电跑的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月15日(周日) 晚上11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YuzukiHD/Buildroot-YuzukiSBC] 无法进入系统 (Issue #6)




 
请提供板子型号，芯片型号，启动设备等参数

**Comment by Leader-txt** [comment]
![IMG_20220516_192438](https://user-images.githubusercontent.com/61892152/168583059-41805a50-1759-401d-a627-61971164a341.jpg)
目前卡在这一步，使用的是最新的镜像
